# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'korg.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy, time
from var import readConfig
import audioController
from pycaw.pycaw import AudioUtilities, ISimpleAudioVolume, IAudioEndpointVolume, IAudioEndpointVolumeCallback
from comtypes import CLSCTX_ALL
from ctypes import cast, POINTER

appName = readConfig()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(689, 375)
        MainWindow.setStyleSheet("background-color: rgb(38, 38, 38);\n"
"color: rgb(175, 175, 175);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("background-color: rgb(38, 38, 38);")
        self.centralwidget.setObjectName("centralwidget")
        self.AppName3 = QtWidgets.QLabel(self.centralwidget)
        self.AppName3.setGeometry(QtCore.QRect(10, 130, 151, 16))
        self.AppName3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AppName3.setStyleSheet("color: rgb(255, 255, 255);")
        self.AppName3.setObjectName("AppName3")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(-10, 150, 831, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.AppName4 = QtWidgets.QLabel(self.centralwidget)
        self.AppName4.setGeometry(QtCore.QRect(10, 170, 151, 16))
        self.AppName4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AppName4.setStyleSheet("color: rgb(255, 255, 255);")
        self.AppName4.setObjectName("AppName4")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(-10, 70, 831, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.AppName6 = QtWidgets.QLabel(self.centralwidget)
        self.AppName6.setGeometry(QtCore.QRect(10, 250, 151, 16))
        self.AppName6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AppName6.setStyleSheet("color: rgb(255, 255, 255);")
        self.AppName6.setObjectName("AppName6")
        self.AppSlider1 = QtWidgets.QSlider(self.centralwidget)
        self.AppSlider1.setGeometry(QtCore.QRect(200, 50, 411, 16))
        self.AppSlider1.setOrientation(QtCore.Qt.Horizontal)
        self.AppSlider1.setObjectName("AppSlider1")
        self.AppSlider7 = QtWidgets.QSlider(self.centralwidget)
        self.AppSlider7.setGeometry(QtCore.QRect(200, 290, 411, 16))
        self.AppSlider7.setOrientation(QtCore.Qt.Horizontal)
        self.AppSlider7.setObjectName("AppSlider7")
        self.AppName0 = QtWidgets.QLabel(self.centralwidget)
        self.AppName0.setGeometry(QtCore.QRect(10, 10, 151, 16))
        self.AppName0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AppName0.setStyleSheet("color: rgb(255, 255, 255);")
        self.AppName0.setObjectName("AppName0")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(-10, 230, 831, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.AppSlider2 = QtWidgets.QSlider(self.centralwidget)
        self.AppSlider2.setGeometry(QtCore.QRect(200, 90, 411, 16))
        self.AppSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.AppSlider2.setObjectName("AppSlider2")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(-10, 310, 831, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.AppName2 = QtWidgets.QLabel(self.centralwidget)
        self.AppName2.setGeometry(QtCore.QRect(10, 90, 151, 16))
        self.AppName2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AppName2.setStyleSheet("color: rgb(255, 255, 255);")
        self.AppName2.setObjectName("AppName2")
        self.AppSlider6 = QtWidgets.QSlider(self.centralwidget)
        self.AppSlider6.setGeometry(QtCore.QRect(200, 250, 411, 16))
        self.AppSlider6.setOrientation(QtCore.Qt.Horizontal)
        self.AppSlider6.setObjectName("AppSlider6")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-10, 30, 831, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(-10, 190, 831, 20))
        self.line_7.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.AppSlider5 = QtWidgets.QSlider(self.centralwidget)
        self.AppSlider5.setGeometry(QtCore.QRect(200, 210, 411, 16))
        self.AppSlider5.setOrientation(QtCore.Qt.Horizontal)
        self.AppSlider5.setObjectName("AppSlider5")
        self.AppName1 = QtWidgets.QLabel(self.centralwidget)
        self.AppName1.setGeometry(QtCore.QRect(10, 50, 151, 16))
        self.AppName1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AppName1.setStyleSheet("color: rgb(255, 255, 255);")
        self.AppName1.setObjectName("AppName1")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(-10, 270, 831, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(-10, 110, 831, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.AppSlider3 = QtWidgets.QSlider(self.centralwidget)
        self.AppSlider3.setGeometry(QtCore.QRect(200, 130, 411, 16))
        self.AppSlider3.setOrientation(QtCore.Qt.Horizontal)
        self.AppSlider3.setObjectName("AppSlider3")
        self.AppSlider4 = QtWidgets.QSlider(self.centralwidget)
        self.AppSlider4.setGeometry(QtCore.QRect(200, 170, 411, 16))
        self.AppSlider4.setOrientation(QtCore.Qt.Horizontal)
        self.AppSlider4.setObjectName("AppSlider4")
        self.AppName7 = QtWidgets.QLabel(self.centralwidget)
        self.AppName7.setGeometry(QtCore.QRect(10, 290, 151, 16))
        self.AppName7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AppName7.setStyleSheet("color: rgb(255, 255, 255);")
        self.AppName7.setObjectName("AppName7")
        self.AppSlider0 = QtWidgets.QSlider(self.centralwidget)
        self.AppSlider0.setGeometry(QtCore.QRect(200, 10, 411, 16))
        self.AppSlider0.setOrientation(QtCore.Qt.Horizontal)
        self.AppSlider0.setObjectName("AppSlider0")
        self.AppName5 = QtWidgets.QLabel(self.centralwidget)
        self.AppName5.setGeometry(QtCore.QRect(10, 210, 151, 16))
        self.AppName5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AppName5.setStyleSheet("color: rgb(255, 255, 255);")
        self.AppName5.setObjectName("AppName5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(160, -20, 20, 341))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lcdNumber0 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber0.setGeometry(QtCore.QRect(620, 10, 64, 23))
        self.lcdNumber0.setObjectName("lcdNumber0")
        self.lcdNumber1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber1.setGeometry(QtCore.QRect(620, 50, 64, 23))
        self.lcdNumber1.setObjectName("lcdNumber1")
        self.lcdNumber2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber2.setGeometry(QtCore.QRect(620, 90, 64, 23))
        self.lcdNumber2.setObjectName("lcdNumber2")
        self.lcdNumber3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber3.setGeometry(QtCore.QRect(620, 130, 64, 23))
        self.lcdNumber3.setObjectName("lcdNumber3")
        self.lcdNumber4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber4.setGeometry(QtCore.QRect(620, 170, 64, 23))
        self.lcdNumber4.setObjectName("lcdNumber4")
        self.lcdNumber5 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber5.setGeometry(QtCore.QRect(620, 210, 64, 23))
        self.lcdNumber5.setObjectName("lcdNumber5")
        self.lcdNumber6 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber6.setGeometry(QtCore.QRect(620, 250, 64, 23))
        self.lcdNumber6.setObjectName("lcdNumber6")
        self.lcdNumber7 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber7.setGeometry(QtCore.QRect(620, 290, 64, 23))
        self.lcdNumber7.setObjectName("lcdNumber7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.updateLcd(MainWindow)
        
        self.all_slider = [
            self.AppSlider0,
            self.AppSlider1,
            self.AppSlider2,
            self.AppSlider3,
            self.AppSlider4,
            self.AppSlider5,
            self.AppSlider6,
            self.AppSlider7,
        ]

        for i, slider in enumerate(self.all_slider):
            print(slider.value())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.all_labels = [
            self.AppName0,
            self.AppName1,
            self.AppName2,
            self.AppName3,
            self.AppName4,
            self.AppName5,
            self.AppName6,
            self.AppName7
        ]
        for i, label in enumerate(self.all_labels):
            label.setText(appName[i])

        self.all_lcds = [
            self.lcdNumber0,
            self.lcdNumber1,
            self.lcdNumber2,
            self.lcdNumber3,
            self.lcdNumber4,
            self.lcdNumber5,
            self.lcdNumber6,
            self.lcdNumber7
        ]

    def updateLcd(self, MainWindow):
        for i, lcd in enumerate(ui.all_lcds):    
            sessions = AudioUtilities.GetAllSessions()
            for session in sessions:            
                devices = AudioUtilities.GetSpeakers()
                interface = devices.Activate(IAudioEndpointVolume._iid_, CLSCTX_ALL, None)
                volume = session._ctl.QueryInterface(ISimpleAudioVolume)
                if session.Process and session.Process.name() == appName[i]:
                    lautst = volume.GetMasterVolume()
                    app.processEvents()
                    lcd.display(lautst * 100)

                    print(appName[i], lautst * 100)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    while True:
        print("test")
        ui.updateLcd(MainWindow)
        time.sleep(1)
    sys.exit(app.exec_())